/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PUsernameRouteImport } from './routes/p/$username'
import { Route as LegalMentionsLegalesRouteImport } from './routes/legal/mentions-legales'
import { Route as LegalConfidentialiteRouteImport } from './routes/legal/confidentialite'
import { Route as LegalCguRouteImport } from './routes/legal/cgu'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedMyListsRouteImport } from './routes/_authenticated/my-lists'
import { Route as AuthenticatedGiftsIOfferRouteImport } from './routes/_authenticated/gifts-i-offer'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedCirclesIndexRouteImport } from './routes/_authenticated/circles/index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedCirclesCircleIdRouteImport } from './routes/_authenticated/circles/$circleId'
import { Route as AuthenticatedCirclesCircleIdIndexRouteImport } from './routes/_authenticated/circles/$circleId.index'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksPurgeStorageRouteImport } from './routes/api/public/hooks/purge-storage'
import { Route as AuthenticatedCirclesCircleIdMembersUserIdRouteImport } from './routes/_authenticated/circles/$circleId.members.$userId'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PUsernameRoute = PUsernameRouteImport.update({
  id: '/p/$username',
  path: '/p/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsLegalesRoute = LegalMentionsLegalesRouteImport.update({
  id: '/legal/mentions-legales',
  path: '/legal/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConfidentialiteRoute = LegalConfidentialiteRouteImport.update({
  id: '/legal/confidentialite',
  path: '/legal/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCguRoute = LegalCguRouteImport.update({
  id: '/legal/cgu',
  path: '/legal/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyListsRoute = AuthenticatedMyListsRouteImport.update({
  id: '/my-lists',
  path: '/my-lists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGiftsIOfferRoute =
  AuthenticatedGiftsIOfferRouteImport.update({
    id: '/gifts-i-offer',
    path: '/gifts-i-offer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCirclesIndexRoute =
  AuthenticatedCirclesIndexRouteImport.update({
    id: '/circles/',
    path: '/circles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCirclesCircleIdRoute =
  AuthenticatedCirclesCircleIdRouteImport.update({
    id: '/circles/$circleId',
    path: '/circles/$circleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCirclesCircleIdIndexRoute =
  AuthenticatedCirclesCircleIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCirclesCircleIdRoute,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPurgeStorageRoute =
  ApiPublicHooksPurgeStorageRouteImport.update({
    id: '/api/public/hooks/purge-storage',
    path: '/api/public/hooks/purge-storage',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCirclesCircleIdMembersUserIdRoute =
  AuthenticatedCirclesCircleIdMembersUserIdRouteImport.update({
    id: '/members/$userId',
    path: '/members/$userId',
    getParentRoute: () => AuthenticatedCirclesCircleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/gifts-i-offer': typeof AuthenticatedGiftsIOfferRoute
  '/my-lists': typeof AuthenticatedMyListsRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/p/$username': typeof PUsernameRoute
  '/circles/$circleId': typeof AuthenticatedCirclesCircleIdRouteWithChildren
  '/api/public/health': typeof ApiPublicHealthRoute
  '/circles/': typeof AuthenticatedCirclesIndexRoute
  '/api/public/hooks/purge-storage': typeof ApiPublicHooksPurgeStorageRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/circles/$circleId/': typeof AuthenticatedCirclesCircleIdIndexRoute
  '/circles/$circleId/members/$userId': typeof AuthenticatedCirclesCircleIdMembersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/gifts-i-offer': typeof AuthenticatedGiftsIOfferRoute
  '/my-lists': typeof AuthenticatedMyListsRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/p/$username': typeof PUsernameRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/circles': typeof AuthenticatedCirclesIndexRoute
  '/api/public/hooks/purge-storage': typeof ApiPublicHooksPurgeStorageRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/circles/$circleId': typeof AuthenticatedCirclesCircleIdIndexRoute
  '/circles/$circleId/members/$userId': typeof AuthenticatedCirclesCircleIdMembersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/gifts-i-offer': typeof AuthenticatedGiftsIOfferRoute
  '/_authenticated/my-lists': typeof AuthenticatedMyListsRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/p/$username': typeof PUsernameRoute
  '/_authenticated/circles/$circleId': typeof AuthenticatedCirclesCircleIdRouteWithChildren
  '/api/public/health': typeof ApiPublicHealthRoute
  '/_authenticated/circles/': typeof AuthenticatedCirclesIndexRoute
  '/api/public/hooks/purge-storage': typeof ApiPublicHooksPurgeStorageRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/_authenticated/circles/$circleId/': typeof AuthenticatedCirclesCircleIdIndexRoute
  '/_authenticated/circles/$circleId/members/$userId': typeof AuthenticatedCirclesCircleIdMembersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/reset-password'
    | '/status'
    | '/account'
    | '/admin'
    | '/gifts-i-offer'
    | '/my-lists'
    | '/people'
    | '/profile'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/legal/mentions-legales'
    | '/p/$username'
    | '/circles/$circleId'
    | '/api/public/health'
    | '/circles/'
    | '/api/public/hooks/purge-storage'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/circles/$circleId/'
    | '/circles/$circleId/members/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/reset-password'
    | '/status'
    | '/account'
    | '/admin'
    | '/gifts-i-offer'
    | '/my-lists'
    | '/people'
    | '/profile'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/legal/mentions-legales'
    | '/p/$username'
    | '/api/public/health'
    | '/circles'
    | '/api/public/hooks/purge-storage'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/circles/$circleId'
    | '/circles/$circleId/members/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/discover'
    | '/reset-password'
    | '/status'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/gifts-i-offer'
    | '/_authenticated/my-lists'
    | '/_authenticated/people'
    | '/_authenticated/profile'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/legal/mentions-legales'
    | '/p/$username'
    | '/_authenticated/circles/$circleId'
    | '/api/public/health'
    | '/_authenticated/circles/'
    | '/api/public/hooks/purge-storage'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/_authenticated/circles/$circleId/'
    | '/_authenticated/circles/$circleId/members/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StatusRoute: typeof StatusRoute
  LegalCguRoute: typeof LegalCguRoute
  LegalConfidentialiteRoute: typeof LegalConfidentialiteRoute
  LegalMentionsLegalesRoute: typeof LegalMentionsLegalesRoute
  PUsernameRoute: typeof PUsernameRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicHooksPurgeStorageRoute: typeof ApiPublicHooksPurgeStorageRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$username': {
      id: '/p/$username'
      path: '/p/$username'
      fullPath: '/p/$username'
      preLoaderRoute: typeof PUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions-legales': {
      id: '/legal/mentions-legales'
      path: '/legal/mentions-legales'
      fullPath: '/legal/mentions-legales'
      preLoaderRoute: typeof LegalMentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/confidentialite': {
      id: '/legal/confidentialite'
      path: '/legal/confidentialite'
      fullPath: '/legal/confidentialite'
      preLoaderRoute: typeof LegalConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgu': {
      id: '/legal/cgu'
      path: '/legal/cgu'
      fullPath: '/legal/cgu'
      preLoaderRoute: typeof LegalCguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-lists': {
      id: '/_authenticated/my-lists'
      path: '/my-lists'
      fullPath: '/my-lists'
      preLoaderRoute: typeof AuthenticatedMyListsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gifts-i-offer': {
      id: '/_authenticated/gifts-i-offer'
      path: '/gifts-i-offer'
      fullPath: '/gifts-i-offer'
      preLoaderRoute: typeof AuthenticatedGiftsIOfferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/circles/': {
      id: '/_authenticated/circles/'
      path: '/circles'
      fullPath: '/circles/'
      preLoaderRoute: typeof AuthenticatedCirclesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/circles/$circleId': {
      id: '/_authenticated/circles/$circleId'
      path: '/circles/$circleId'
      fullPath: '/circles/$circleId'
      preLoaderRoute: typeof AuthenticatedCirclesCircleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/circles/$circleId/': {
      id: '/_authenticated/circles/$circleId/'
      path: '/'
      fullPath: '/circles/$circleId/'
      preLoaderRoute: typeof AuthenticatedCirclesCircleIdIndexRouteImport
      parentRoute: typeof AuthenticatedCirclesCircleIdRoute
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/purge-storage': {
      id: '/api/public/hooks/purge-storage'
      path: '/api/public/hooks/purge-storage'
      fullPath: '/api/public/hooks/purge-storage'
      preLoaderRoute: typeof ApiPublicHooksPurgeStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/circles/$circleId/members/$userId': {
      id: '/_authenticated/circles/$circleId/members/$userId'
      path: '/members/$userId'
      fullPath: '/circles/$circleId/members/$userId'
      preLoaderRoute: typeof AuthenticatedCirclesCircleIdMembersUserIdRouteImport
      parentRoute: typeof AuthenticatedCirclesCircleIdRoute
    }
  }
}

interface AuthenticatedCirclesCircleIdRouteChildren {
  AuthenticatedCirclesCircleIdIndexRoute: typeof AuthenticatedCirclesCircleIdIndexRoute
  AuthenticatedCirclesCircleIdMembersUserIdRoute: typeof AuthenticatedCirclesCircleIdMembersUserIdRoute
}

const AuthenticatedCirclesCircleIdRouteChildren: AuthenticatedCirclesCircleIdRouteChildren =
  {
    AuthenticatedCirclesCircleIdIndexRoute:
      AuthenticatedCirclesCircleIdIndexRoute,
    AuthenticatedCirclesCircleIdMembersUserIdRoute:
      AuthenticatedCirclesCircleIdMembersUserIdRoute,
  }

const AuthenticatedCirclesCircleIdRouteWithChildren =
  AuthenticatedCirclesCircleIdRoute._addFileChildren(
    AuthenticatedCirclesCircleIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedGiftsIOfferRoute: typeof AuthenticatedGiftsIOfferRoute
  AuthenticatedMyListsRoute: typeof AuthenticatedMyListsRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedCirclesCircleIdRoute: typeof AuthenticatedCirclesCircleIdRouteWithChildren
  AuthenticatedCirclesIndexRoute: typeof AuthenticatedCirclesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedGiftsIOfferRoute: AuthenticatedGiftsIOfferRoute,
  AuthenticatedMyListsRoute: AuthenticatedMyListsRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedCirclesCircleIdRoute:
    AuthenticatedCirclesCircleIdRouteWithChildren,
  AuthenticatedCirclesIndexRoute: AuthenticatedCirclesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StatusRoute: StatusRoute,
  LegalCguRoute: LegalCguRoute,
  LegalConfidentialiteRoute: LegalConfidentialiteRoute,
  LegalMentionsLegalesRoute: LegalMentionsLegalesRoute,
  PUsernameRoute: PUsernameRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicHooksPurgeStorageRoute: ApiPublicHooksPurgeStorageRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
